name: Global Pipeline
on: 
  push:
    branches: [ $default-branch ]
  workflow_dispatch: # Allows manual triggers

jobs:
  everything:
    # We use the SHA for the "Chain of Trust"
    uses: cert-labs-hq/automations-repo/.github/workflows/universal-orchestrator.yml@V1
    secrets: inherit